print("########## 1.2.1 ##########")
name = input("What is your name? ")
print(name)
print(name)

print("########## 1.2.2 ##########")
name = input("What is your name? ")
print(name)
print("!" + name + "!" + name + "!" )
print("########## 1.2.3 ##########")
namefirst = input("what is your first name:")
namelast = input("what is your last name:")
address = input("what is your street address:")
state = input("what is your address state:")
zipcode = input("what is your zip code:")
print(namefirst + " "  + namelast)
print(address)
print(state + "," + zipcode)
print("########## 1.2.4 ##########")

# Fix the code
part1 = input("The 1st part: ")
part2 = input("The 2nd part: ")
part3 = input("The 3rd part: ")
print(part1 + "-" + part2 + "-" + part3)

print("########## 1.2.5 ##########")
name = input("please type in a name:")
year = input("please type in a year:")
print(name + " is a valiant knight, born in the year " + year + ". One morning " + name + " woke up to an awful racket: a dragon was approaching the village. Only " + name + " could save the village's residents.")
